### PR TITLE
Greentea / Caffe with OpenCL benchmarks

### PR DESCRIPTION
**Pull request by naibaf7**
This adds benchmarking for https://github.com/naibaf7/caffe (see also: https://github.com/BVLC/caffe/pull/2610)
It is called project Greentea and contains a complete OpenCL backend for Caffe.

Tested & found working on Fedora 22 & Ubuntu 14.04. The installation script is written so that it should work on Ubuntu 13.04 to 15.04. On Fedora 22, the packages need to be installed manually.

The biggest pitfall here is a faulty OpenCL installation and/or incompatible libraries. Make sure to install CUDA & nVidia drivers respectievly FGLRX for AMD correctly first.

Note that it will be quite a bit slower than Caffe with CUDA. The OpenCL backend is still a work-in-progress project. The standard compilation also uses ViennaCL-BLAS for simplicity which is often slower than AMD's clBLAS.

### CODE REVIEW

**Comment by hughperkins** [comment]
I am not benchmarks maintainer, just an onlooker, but I reckon you might want to do everything you can so you longer need to write:
```
Tested & found working on Fedora 22. The installation script is written 
so that it should theoretically work on Ubuntu 13.04 to 15.04, but is not tested yet.
The biggest pitfall here is a faulty OpenCL installation and/or incompatible libraries.
```
The benchmarks run on Ubuntu 14.04, against an NVIDIA GPU.  You can run up a GPU instance on Amazon for 65 cents an hour http://aws.amazon.com/ec2/pricing/  I'm happy to pay for one for a day or two, and grant you access.

**Comment by naibaf7** [comment]
@hughperkins 
Thanks, I'll try that out.

**Comment by hughperkins** [comment]
Ok.  Hmmm, you have benchmarks for all the sections, including overfeat, and vgg.  That's cool :-)

**Comment by naibaf7** [comment]
@hughperkins 
Yes, but I saw my OpenCL kernels are not really optimized for that types of networks, as I mainly focussed on getting this fast:
https://github.com/naibaf7/caffe_neural_models

But we'll see, there's definitely room for kernel optimization. At least it runs all networks without problems.

**Comment by naibaf7** [comment]
@hughperkins 
OK, tested on Ubuntu 14.04 on Amazon AWS EC2 g2.2 GPU.
Once the CUDA driver and ICD loader are installed (should be fine when CUDA 7.0 is set up) then it works.

**Comment by hughperkins** [comment]
Cool :-)

**Comment by soumith** [comment]
thanks a lot for this Fabian. You made my life much easier with this. Looking forward to benchmarking this.

**Comment by naibaf7** [comment]
@soumith 
Cool :)
Yeah, but it won't be very fast... it's a start though. At least it's very versatile :)

**Pull request merged**
