### PR TITLE
Add missing padding

### PR DESCRIPTION
**Pull request by ozabluda**

### CODE REVIEW

**Comment by ozabluda** [comment]
Only the first commit "Add missing padding" was meant to go into this PR. I am trying to figure out how to remove the other two commits from this PR.

**Comment by ozabluda** [comment]
Removed the other two commits. Now this PR contains exactly one correct commit.

**Comment by soumith** [comment]
thanks!

**Comment by ozabluda** [comment]
Now greentea directory is out-of sync with caffe directory, due to files duplicated in greentea directory (vgg_a.prototxt, alexnet.prototxt, etc). I can submit a PR removing those and other duplicate files, and using files in ../caffe instead, but I am not sure if @naibaf7 plans on changing the copy of the files in the future with greentea-specific things.

**Comment by naibaf7** [comment]
@ozabluda 
for the close future it is safe to assume Greentea can always use the same protobuf files as original Caffe.

**Pull request merged**
